# Generated by Django 5.0.1 on 2024-02-09 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('post', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='postlikes', to='network.post')),
                ('who', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
