# Generated by Django 5.0.1 on 2024-02-13 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_user_followers_alter_user_followings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='amount',
        ),
    ]
