# Generated by Django 5.0.1 on 2024-01-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auction_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='satus',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='title',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
