# Generated by Django 5.0.1 on 2024-01-29 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_bid_remove_auction_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.bid'),
        ),
    ]
