# Generated by Django 5.0.1 on 2024-01-30 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auction_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='bid',
            new_name='price',
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userBids', to=settings.AUTH_USER_MODEL),
        ),
    ]
