# Generated by Django 5.0.1 on 2024-01-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=500)),
                ('bid', models.DecimalField(decimal_places=10, max_digits=19)),
                ('image', models.URLField(blank=True)),
                ('category', models.ManyToManyField(blank=True, related_name='incategory', to='auctions.category')),
            ],
        ),
    ]
