# Generated by Django 5.0.1 on 2024-01-29 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='category',
        ),
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(blank=True, default='Other', on_delete=django.db.models.deletion.CASCADE, related_name='incategory', to='auctions.category'),
        ),
    ]
