# Generated by Django 5.0.1 on 2024-01-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auction_satus_alter_auction_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='satus',
            field=models.CharField(default='Active', max_length=30),
        ),
    ]
