# Generated by Django 5.0.1 on 2024-01-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auction_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.DecimalField(decimal_places=1, max_digits=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='auction',
            name='bid',
        ),
    ]
